language: ruby
dist: trusty
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- docker build -f java/tomcat/Dockerfile -t genexus/javatomcat:travis java/tomcat
after_script:
- docker push genexus/javatomcat:travis
env:
  global:
    secure: qFIOZVhPFFzwZW8kalHQtXIfX/TZubl/Xc3hnLsAdufoLiBctu2S09SQKUUnn/4jqMt/DEPnQfIP7X6IBc8Igu0eiwqorFp16SnxbSZho21aQZ+S6qTxkrjGJn+clgDY3qB/Pri+vfubvIPEdoygKtis52UOT6gWWoQJWqhyX5tjO9fbKTt6LjSXFr7/PyoXBifJGlHMu3GHKsO3Nc5tWN1mfQHkNDq33VxwnuG6GuGg5c7uOW947u3A9uLwvzmGcpluul6Timcs0LkR7eVd9QMRlBWAP8a0tbxfdvNPrw6vsuKe9QN8ilKzOiv9+2SFS0P69jxtFghuUou6l3KRiN5QfqwCNfHOOSN/g5jzMEmV17tA8fb2zVH3qV+E9bbuLRICkNOyApUShvGUxU9IENvfQXX+ijX6NnCl0G5MTV+ZV63vmzl/3M/A4yYDKG3T9Z5dITX2MK6Rv5BSbLTHQD7k8TKzrjevorHk1vwopaJIrulERM4YjN3AOsj/arcJKnwZl29teo55TkEacgB16jURL7rnod+z4mVPZhP1XTECNoeV50tqcuPcs6zq2txxi8MaNHlRaxd38hv9NqnkWewNrM7fXdjIzFmqmFDegRpUdg/h9Y74vnUOT9qbh9L/RKmzSjJ7WQxGqPNDZpMmQHgTmByx0bqDp3QB4mwK/KU=
