# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  javaImage: 'genexus/javatomcat:8.5'
  netCoreImage: 'genexus/netcore:2.1.1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build --file ./java/tomcat/Dockerfile --build-arg BUILD_DATE=$(Build.BuildNumber) -t $(javaImage) ./java/tomcat/
  displayName: 'Build Java image'
- script: docker build --file './.net core/Dockerfile' --build-arg BUILD_DATE=$(Build.BuildNumber) -t $(netCoreImage) './.net core'
  displayName: 'Build .NET Core image'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
