# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - java/*

variables:
  javaImage: 'genexus/javatomcat:9-jre11'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build --file ./java/tomcat/Dockerfile --build-arg BUILD_DATE=$(Build.BuildNumber) -t $(javaImage) ./java/tomcat/
  displayName: 'Build Java image'

