FROM microsoft/aspnet:4.6.2

LABEL com.genexus.name: "Genexus .NET Web" \
      com.genexus.description: "Genexus Docker Compose file for .NET Framework environments" 
      com.genexus.url: "http://www.genexus.com/"
      com.genexus.vcs-url: "https://github.com/genexuslabs/dockerfiles"
      com.genexus.vendor: "GeneXus"
      com.genexus.schema-version: "1.0" 
      com.genexus.maintainer: "Seba Gómez <sgomez@genexus.com>"

ADD https://github.com/Microsoft/iis-docker/raw/d6580f65bdf060213cd8053762591ac8b5e94746/windowsservercore/ServiceMonitor.exe /